# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMLTivPesvcCLCMXgSnNzSqL9RmOZNsj
"""

numero1 = float (input("Digite o numero1"))
numero2 = float (input("Digite o numero2"))

soma = (numero1 + numero2)

if soma > 15:
  print("A soma e maior que 15")
else:
    print("A soma nao e maior que 15")

numero = float (input("Digite um numero inteiro"))

if numero == 0:
  print("numero neutro")

elif numero > 0:
  print("numero positivo")

elif numero < 0:
  print("numero negativo")

idade = float (input("Digite sua idade"))

if idade >= 18:
  print("Voce e maior de idade")

else:
  print("Voce nao e maior de idade")

temperatura = float (input("Digite a Temperatura atual"))

if temperatura > 30:
  print("Esta quente")
elif temperatura < 15:
  print("Esta Frio")
elif temperatura > 15 < 30:
  print("Esta uma temperatura agradavel")

n1 = float (input("Digite o numero1"))
n2 = float (input("Digite o numero2"))

if n1 == n2:
  print("Os numero sao iguais")
else:
  print("Os numero sao diferentes")

senha = float (input("Digite a senha"))

if senha == 1234:
  print("ACESSO PERMITIDO")
else:
  print("ACESSO NEGADO")

n1 = float (input("Digite a nota1"))
n2 = float (input("Digite a nota2"))

media = (n1 + n2) /2
print(f"Sua media e {media}")

if media >= 7:
  print("Aprovado")
elif media >= 5 < 7:
  print("Voce esta de exame")
elif media < 5:
  print("Voce esta repovado")

time1 = int(input("Gols time1"))
time2 = int(input("Gols time2"))

if time1 == time2:
  print("A partida empatou")
elif time1 > time2:
  print("Time1 ganhou a partida")
else:
  print("Time2 ganhou a partida")

turno = (input("Qual turno voce estuda?")).title()


if turno == "Matutino":
  print("Bom dia")
elif turno == "Vespertino":
  print("Boa Tarde")
elif turno == "Noturno":
  print("Boa noite")
else:
  print("Formato invalido")

resultado = str(input("Digite o placar do jogo"))

time1 = int(resultado[0])
time2 = int(resultado[-1])

if time1 == time2:
  print("A partida empatou")
elif time1 > time2:
  print("Time1 ganhou a partida")
else:
  print("Time2 ganhou a partida")

idade = int(input("Digite a sua idade"))


if idade >= 0 and idade <= 11:
  print("Crianca")
elif idade >= 12 and idade <= 18:
  print("Adolescente")
elif idade >= 19 and idade <= 24:
  print("Jovem")
elif idade >= 25 and idade <= 40:
  print("Adulto")
elif idade >= 41 and idade <= 60:
  print("Meia idade")
elif idade >= 60:
  print("Idoso")

salario = float(input("Digite o seu salario para calcular o reajuste"))

if salario < 280:
  print(f"seu salario R${salario:.2f}")
  print("o percentual do aumento e de 20%")
  aumento = (salario / 100 * 20)
  print(f"o valor do aumento e de {aumento}")
  print(f"o salario com reajuste R${salario + aumento:.2f}")

elif salario > 279 and salario <= 700:
  print(f"seu salario R${salario:.2f}")
  print("o percentual do aumento e de 15%")
  aumento = (salario / 100 * 15)
  print(f"o valor do aumento e de {aumento}")
  print(f"o salario com reajusto R${salario + aumento:.2f}")

elif salario > 699 and salario <= 1500:
  print(f"seu salario R${salario:.2f}")
  print("o percentual do aumento e de 10%")
  aumento = (salario / 100 * 10)
  print(f"o valor do aumento e de {aumento}")
  print(f"o salario com reajusto R${salario + aumento:.2f}")

elif salario >= 1500:
  print(f"seu salario R${salario:.2f}")
  print("o percentual do aumento e de 5%")
  aumento = (salario / 100 * 5)
  print(f"o valor do aumento e de {aumento}")
  print(f"o salario com reajusto R${salario + aumento:.2f}")

print("Responda as seguintes perguntas com sim ou nao:")

pergunta1 = input("Telefonou para a vitima?").lower()
pergunta2 = input("Esteve no local do crime?").lower()
pergunta3 = input("Mora perto da vitima?").lower()
pergunta4 = input("Devia para a vitima?").lower()
pergunta5 = input("Ja trabalhou com a vitima?").lower()

positivas = 0

if pergunta1 == "sim":
  positivas += 1
if pergunta2 == "sim":
  positivas += 1
if pergunta3 == "sim":
  positivas += 1
if pergunta4 == "sim":
  positivas += 1
if pergunta5 == "sim":
  positivas += 1

if positivas == 2:
  print("Suspeita")
elif 3 <= positivas <= 4:
 print("Cumplice")
elif positivas == 5:
  print("Bandindinho")
else:
  print("inocente")

semana = int(input("Digite um numero para saber o dia da semana"))


if semana == 1:
  print("1-Domingo")
elif semana == 2:
  print("2-Segunda-Feira")
elif semana == 3:
  print("3-Terca-Feira")
elif semana == 4:
  print("4-Quarta-Feira")
elif semana == 5:
  print("5-Quinta-Feira")
elif semana == 6:
  print("6-Sexta-Feira")
elif semana <= 0 or semana >= 7:
  print("Valor invalido")

escolha = int(input("Digite 1 para Celsius e 2 para Fahrenheit"))

if escolha == 1:
  c1 = float(input("Conversao de C para F"))
  f = c1 * 1.8 + 32
  print(f"A conversao para Fahrenheit: {f:.2f}")
elif escolha == 2:
  c2 = float(input("Conversao de F para C"))
  c = (c2 - 32) / 1.8
  print(f"A conversao para Celsiu: {c:.2f}")

idade = int(input("Digite a sua idade e confira se deve votar ou nao"))


if idade < 16:
  print("Proibido votar")
elif idade <= 16 and idade < 18:
  print("Seu voto e optativo")
elif idade >= 18 and idade < 65:
  print("Seu voto e obrigatorio")
elif idade >= 65:
  print("Seu voto e optativo")

p1 = float(input("Digite o valor do produto1"))
p2 = float(input("Digite o valor do produto2"))
p3 = float(input("Digite o valor do produto3"))

if p1 < p2 and p1 < p3:
  print("O produto 1 e o mais barato")
elif p2 < p1 and p2 < p3:
  print("O produto 2 mais barato")
elif p3 < p1 and p3 < p2:
  print("O produto 3 mais barato")